### ISSUE TITLE
Small issues due to WP 5.8 upgrade

### ISSUE THREAD

**Issue by cjyabraham** [lfph/lfph.io#108]
1. The tables on the [Become a Member](https://www.lfph.io/join/become-a-member/) page lost their coloring.  They used to look like this:
<img width="840" alt="Screen Shot 2021-07-31 at 11 12 12 AM" src="https://user-images.githubusercontent.com/463160/127744301-96491e7c-259f-4588-954c-98da02ef9589.png">

2. The second chart on the [Host your project](https://www.lfph.io/join/host-your-project/) page seems to have floated up.  It should look like this:
<img width="1066" alt="Screen Shot 2021-07-31 at 11 23 44 AM" src="https://user-images.githubusercontent.com/463160/127744599-c4624dcf-201e-41a2-9a97-8cf078bdef0c.png">

**Comment by cjyabraham** [comment]
I fixed 2 by putting the images in a columns block instead of using the Gallery block.

**Comment by thetwopct** [comment]
1. This was a deliberate change to keep in sync with CNCF and the blue/purple was a bit overbearing. Can switch it back, but think it looks good like it is.

2. May need to check the reports on CNCF as they make use of this Gallery style. There is updated styling for the Gallery block from Core; this should solve it and align images inside Gallery to the bottom again

```
.blocks-gallery-grid .blocks-gallery-item, .wp-block-gallery .blocks-gallery-item {
align-self: unset;
}

```

**Comment by cjyabraham** [comment]
1. Ok.  I've added a header section to each table as that seemed to have been lost in the change.  I think it looks good now.
2. As mentioned, I've converted to columns which do the job nicely.
