### ISSUE TITLE
External link icons in the footer are too bright

### ISSUE THREAD

**Issue by cjyabraham** [lfph/lfph.io#13]
Can we make them the same color as the text:
<img width="397" alt="Screen Shot 2020-06-16 at 3 11 19 PM" src="https://user-images.githubusercontent.com/463160/84742878-b78b0600-afe3-11ea-91ef-2fdba80d3824.png">

**Comment by thetwopct** [comment]
Let’s finalise the design first? 😂 once we’re set on a colour I’ll change them then.

**Comment by cjyabraham** [comment]
this looks done
