### ISSUE TITLE
Fix Safe SVG plugin sizing

### ISSUE THREAD

**Issue by cjyabraham** [lfph/lfph.io#19]
Quoting from @thetwopct in [this issue](https://github.com/lfph/lfph.io/issues/7#issuecomment-644831798):

> But there is a problem in the editor and it seems to be caused by SVG Autocrop.
> 
> When inserting an image, the image dimensions sidebar is updated with the dimensions, and the image is inserted in to the page.
> When SVG Autocrop plugin enabled, an image is inserted at full size, auto-cropped, the dimensions are updated, then the image is inserted again, but the image dimensions are not applied to the image.
> Without dimensions the SVG adopts the minimum image size set by Gutenberg editor - 20px.
> Perhaps the wp_handle_upload_prefilter is being called too late, and it needs to be called before the image is first inserted and the dimensions are updated.

It would be nice to get this fixed.  I assume it will eliminate that large space above SVGs used in featured images as well as fix the sizing of SVGs dropped into posts.  You can check in the fix in the [wp-svg-autocrop repo](https://github.com/cncf/wp-svg-autocrop) and then I can copy over for the WP plugins svn repo and get that updated.

It's not ideal but I created this issue on the lfph board so that it won't drop out of visibility and be forgotten.

**Comment by thetwopct** [comment]
After experimenting with this issue, I can confirm its not SVG Autocrop, it's the Safe SVG plugin, and [others are having the same issues](https://wordpress.org/support/topic/bug-in-svg_dimensions-method/).

**Comment by cjyabraham** [comment]
I've cleaned this issue up and [re-opened it in the cncf project](https://github.com/cncf/cncf.io/issues/219) so will close here.
