### ISSUE TITLE
Allow the twitter feed block to have a configureable twitter account

### ISSUE THREAD

**Issue by cjyabraham** [lfph/lfph.io#20]
Currently the twitter feed block is hardcoded to pull from `https://twitter.com/CloudNativeFdn?ref_src=twsrc%5Etfw`.  Make this configureable as a block attribute.

**Comment by thetwopct** [comment]
An easy fix, but we're not currently using it on either site due to its lack of configuration options / cache, so I had planned to remove it (as the Block name is the same as the Social Feed plugin too, it's confusing)

**Comment by cjyabraham** [comment]
Oh, ok.  Feel free to close this or leave it open as a reminder until you remove it.
