### ISSUE TITLE
Can we keep the external icon together with the text?

### ISSUE THREAD

**Issue by cjyabraham** [lfph/lfph.io#22]
Here's the news items on the homepage but may be an issue elsewhere as well:
<img width="699" alt="Screen Shot 2020-06-26 at 2 25 57 PM" src="https://user-images.githubusercontent.com/463160/85827548-13f6de00-b7b9-11ea-8222-0c005aeb5556.png">

**Comment by thetwopct** [comment]
Fixed, and copied across to CNCF
