### ISSUE TITLE
People popup goes off the screen on mobile and can't be closed

### ISSUE THREAD

**Issue by cjyabraham** [lfph/lfph.io#23]
Using browserstack, try using Samsung Galaxy S10 with Chrome.  Go to [the Staff page](https://pr-5-lfph.pantheonsite.io/about/staff/) and open Dan's profile.  You'll see you can't see all the content or close it:
<img width="333" alt="Screen Shot 2020-07-02 at 9 18 42 AM" src="https://user-images.githubusercontent.com/463160/86305748-0ae88f80-bc45-11ea-97c0-add09388398f.png">

**Comment by thetwopct** [comment]
Fixed on S10, have checked a few more devices and can no longer replicate, so think this is now fixed.
