### ISSUE TITLE
External icon is missing here

### ISSUE THREAD

**Issue by cjyabraham** [lfph/lfph.io#27]
<img width="423" alt="Screen Shot 2020-07-18 at 9 29 02 AM" src="https://user-images.githubusercontent.com/463160/87841605-2d330c00-c8d9-11ea-908e-988cbfc5196a.png">

**Comment by thetwopct** [comment]
FYI I renamed the external icon CSS from `external is-footer` to `external is-white` as it started being used in a few more places. I missed updating it here.
