### ISSUE TITLE
Make the project logos look the same size

### ISSUE THREAD

**Issue by cjyabraham** [lfph/lfph.io#29]
[On the CNCF site, all projects line up along the same line](https://dev-cncfci.pantheonsite.io/projects/).  Could we get [the LFPH ones](https://dev-lfph.pantheonsite.io/join/projects/) to do the same?

**Comment by thetwopct** [comment]
All of the logos on CNCF Projects have the same dimensions, are centered in the canvas and don't include text. The Covid Green logo is not following this process. I was presuming all Projects for CNCF went through some kind of build process where the logos were processed to be consistent and added to to the git repo. Could this process be applied to LFPH project logos too?

**Comment by cjyabraham** [comment]
I believe @alexcontini prepares these for CNCF.  I've asked her to do the same for us here.

**Comment by cjyabraham** [comment]
Alex has [done these](https://dev-lfph.pantheonsite.io/join/projects/).
