### ISSUE TITLE
Hero image on search results uses first featured image from loop

### ISSUE THREAD

**Issue by cjyabraham** [lfph/lfph.io#31]
For some reason the hero image on [search results](https://dev-lfph.pantheonsite.io/?s=test) picks up the featured image of the top item.  Can we ensure it just uses the default hero image?

**Comment by thetwopct** [comment]
"Fix" makes it sound like it wasn't intentional ;)

**Comment by cjyabraham** [comment]
Ok.  I'm so boring, however, I think I could get used to that behavior.
