### ISSUE TITLE
Flying Scripts delay loading for recaptcha

### ISSUE THREAD

**Issue by thetwopct** [lfph/lfph.io#32]
I've implemented Flying Scripts and set it up to delay the following:

- ctf-scripts (custom twitter feed)
- recaptcha__en (recaptcha)
- api.js (related to recaptcha)

Before:
![20200718223903-Measure](https://user-images.githubusercontent.com/10615884/87862396-7cb02100-c947-11ea-8606-70aaf896a258.jpg)

After:
![20200718224421-Measure](https://user-images.githubusercontent.com/10615884/87862457-3a3b1400-c948-11ea-974a-e1e68810cc43.jpg)

Haven't tested the forms, but presumed that will happen as part of https://github.com/lfph/lfph.io/issues/14

**Comment by thetwopct** [comment]
sfmc-forms.js requires recaptcha, but is bundled in to global.js, so delaying recaptcha can cause JS errors. 

If we stop bundling sfmc-forms.js and enqueue as its own file, this would allow us to delay its loading as well as recaptcha. This would allow us to retain the speed improvements of delaying recaptcha.

**Comment by cjyabraham** [comment]
Amazing performance increase, but what about the remaining 3 points??  

The forms seem to work fine currently so I think we don't need to do anything further.

**Comment by cjyabraham** [comment]
I just tested the contact form now and it doesn't work so I've deactivated this plugin for now.

**Comment by cjyabraham** [comment]
deployed

**Comment by cjyabraham** [comment]
this has been done to cncfci

**Comment by cjyabraham** [comment]
I re-tested the performance with and without Flying Scripts:

**Homepage wo Flying Scripts**
<img width="540" alt="Screen Shot 2020-08-08 at 2 36 52 PM" src="https://user-images.githubusercontent.com/463160/89704227-9fe95180-d984-11ea-843f-34450eaa837b.png">
**Homepage with Flying Scripts**
<img width="498" alt="Screen Shot 2020-08-08 at 2 38 01 PM" src="https://user-images.githubusercontent.com/463160/89704246-c9a27880-d984-11ea-83e4-9572fb41ae86.png">

This agrees with the modest improvements I'm getting [on the events site](https://github.com/LF-Engineering/lfevents/issues/563).  I also [retested the load times and you can see a big difference from the ones I did on 7/30](https://docs.google.com/spreadsheets/d/1-YU77OLcdI1mMPRpK6FEjkKS8DMl2m7uuGo0i92iiu8/edit#gid=161007827). 

@thetwopct how did you originally generate your performance numbers above?

Note: I do happen to have super-fast internet right now.  Could that be having an effect?
<img width="521" alt="Screen Shot 2020-08-08 at 2 41 22 PM" src="https://user-images.githubusercontent.com/463160/89704306-47668400-d985-11ea-92e5-96f608875684.png">

**Comment by thetwopct** [comment]
I originated them via web.dev/measure - so independent of connection speed and browser extension issues. 

I can only assume your before and after testing is inaccurate. Did you clear server cache?

**Comment by thetwopct** [comment]
# With Flying Scripts

![20200808110839-Measure](https://user-images.githubusercontent.com/10615884/89707590-884fa000-d967-11ea-9a9c-6062ca89fdb0.jpg)

# Without Flying Scripts

(Deactivate plugin, clear Pantheon cache, visit page in browser to rebuild any hit cache)

![20200808111006-Measure](https://user-images.githubusercontent.com/10615884/89707614-c8af1e00-d967-11ea-811d-1a8a72dbbd0d.jpg)

**Comment by cjyabraham** [comment]
Here's what I got

**Homepage wo FS**
<img width="1019" alt="hp wo fs" src="https://user-images.githubusercontent.com/463160/89723245-391c7480-da26-11ea-9660-da247109084e.png">

**Homepage w FS**
<img width="1027" alt="hp w fs" src="https://user-images.githubusercontent.com/463160/89723247-3f125580-da26-11ea-8fce-27f051252070.png">
