### ISSUE TITLE
Faces image looks blurry when viewport <375px wide

### ISSUE THREAD

**Issue by cjyabraham** [lfph/lfph.io#37]
<img width="323" alt="Screen Shot 2020-07-19 at 12 51 34 PM" src="https://user-images.githubusercontent.com/463160/87867352-a5273200-c9be-11ea-8e37-409a6ebda4f3.png">

**Comment by thetwopct** [comment]
D'oh, I tried to use an existing thumb for small screen sizes, but of course that has a hard crop applied. Fixed now.
