### ISSUE TITLE
Blurry thumbnail on blog listing

### ISSUE THREAD

**Issue by cjyabraham** [lfph/lfph.io#38]
This image looks good on the homepage:
<img width="320" alt="Screen Shot 2020-07-19 at 12 57 32 PM" src="https://user-images.githubusercontent.com/463160/87867459-72ca0480-c9bf-11ea-9201-705aecc41bf9.png">

But on the [blog listing page](https://dev-lfph.pantheonsite.io/blog/) it looks blurry:
<img width="391" alt="Screen Shot 2020-07-19 at 12 58 00 PM" src="https://user-images.githubusercontent.com/463160/87867466-837a7a80-c9bf-11ea-9cf1-f109c03a1c7d.png">

It's especially bad at narrower viewport widths:
<img width="536" alt="Screen Shot 2020-07-19 at 12 58 27 PM" src="https://user-images.githubusercontent.com/463160/87867474-94c38700-c9bf-11ea-8fda-9ca97df9a901.png">

**Comment by thetwopct** [comment]
OK fixed.

**Comment by cjyabraham** [comment]
do we need to regenerate thumbnails again?
