### ISSUE TITLE
Newsletter form fields don't seem to work in IE

### ISSUE THREAD

**Issue by cjyabraham** [lfph/lfph.io#4]
When I try and enter values in the newsletter form fields, nothing happens, at least in Browserstack.  IE users are about 1% of cncf.io users so I'll label this as nice-to-have.

**Comment by thetwopct** [comment]
![20200616233829-Dashboard](https://user-images.githubusercontent.com/10615884/84834950-7bc75f00-b02a-11ea-8b17-3f5e0ef1654d.jpg)

Testing in IE11, the fields do work. On submission, the page redirects to the form destination, and doesn't return the message as AJAX.

**Comment by thetwopct** [comment]
Of course, you meant the landing page! And it was the weird :focus border top causing the issue. I've just pushed an updated CSS file removing the top border styling.

**Comment by cjyabraham** [comment]
Thanks.  Deployed.
