### ISSUE TITLE
Could we make the dateline and byline slightly closer together on smaller widths

### ISSUE THREAD

**Issue by cjyabraham** [lfph/lfph.io#40]
<img width="637" alt="Screen Shot 2020-07-19 at 1 07 07 PM" src="https://user-images.githubusercontent.com/463160/87867570-c6891d80-c9c0-11ea-9350-d0f389f611bc.png">

**Comment by thetwopct** [comment]
![20200719163845-Join with us at Linux Foundation Public Health - Linux Foundation Public Health](https://user-images.githubusercontent.com/10615884/87878773-5093af00-c9de-11ea-8bc9-079ca3aca586.jpg)

**Comment by cjyabraham** [comment]
I was thinking something a bit more like this, leaving a bit more space before the post content starts as well:
<img width="567" alt="Screen Shot 2020-07-20 at 1 45 19 PM" src="https://user-images.githubusercontent.com/463160/87903742-4f6e8a80-ca8f-11ea-86cb-b93c6e8d8e5d.png">

**Comment by thetwopct** [comment]
Think it looks a bit weird, but OK
