### ISSUE TITLE
iMessage shows two thumbnails in shared articles; can this be fixed so it only shows one?

### ISSUE THREAD

**Issue by cjyabraham** [lfph/lfph.io#46]
![image](https://user-images.githubusercontent.com/463160/87889190-f2f57600-ca62-11ea-8dc1-f6a319ce3a30.png)

**Comment by thetwopct** [comment]
So far I am only able to replicate this on our sites that use SEO Framework

**Comment by cjyabraham** [comment]
This has something to do with having more than one `og:image` value in the code:
<img width="905" alt="Screen Shot 2020-07-20 at 5 32 10 PM" src="https://user-images.githubusercontent.com/463160/87922748-01697f00-caaf-11ea-8f79-08bb37920eac.png">

**Comment by cjyabraham** [comment]
This needed to be unchecked in the global SEO settings:
<img width="789" alt="Screen Shot 2020-07-20 at 5 38 11 PM" src="https://user-images.githubusercontent.com/463160/87923293-d7648c80-caaf-11ea-9988-ceac45c2fe6d.png">

Fixed as well for CNCF.
