### ISSUE TITLE
Consider ways to make the charts more accessible

### ISSUE THREAD

**Issue by cjyabraham** [lfph/lfph.io#52]
Right now the charts on [this page](https://dev-lfph.pantheonsite.io/join/host-your-project/) and [other pages](https://dev-lfph.pantheonsite.io/join/join-as-pha/) are just images and are not accessible.  Is it possible to make them more accessible?

**Comment by thetwopct** [comment]
1) The first stage of making any image accessible is to use the tools that WordPress gives you

![20200720084917-Media Library ‹ Linux Foundation Public Health — WordPress](https://user-images.githubusercontent.com/10615884/87912842-f9d1b800-ca65-11ea-8f77-14b2d4ed6e87.jpg)

Alt Text - "A graph showing usage of Kubernetes, OpenStack, Hadoop and Serverless from 2016 until 2020"

You can then use the Description field to [add even more description](https://www.americananthro.org/ImageDescriptions?navItemNumber=25126). So in this case maybe:

Description - "A graph showing usage of Kubernetes, OpenStack, Hadoop and Serverless from 2016 until 2020. The graph shows that the usage of Kubernetes is 5 times more than OpenStack, Hadoop and Serverless"

2) Make them bigger so people with visual impairment can see them. There is no rent on screen real estate and people know how to scroll. The concept of above the fold has been [proven](https://kps3.com/website-myths-the-fold/) [again](http://abovethefold.fyi) and [again](https://intenseminimalism.com/2014/the-fold-fallacy-and-the-law-of-closure/) to be a fallacy etc etc. 

So I would not use a column effect and make them full width and large. People like big pictures.

3) We make them interactive using [Chart.JS](https://github.com/chartjs/Chart.js). Not sure how this would work with throwaway charts (as in, could we make a block that is completely adaptive to chart.js features?), but with charts in Annual Reports etc we could make blocks for the charts to be inserted in to the page to make them more interactive. This wouldn't make graphs/images [more accessible](https://www.chartjs.org/docs/latest/general/accessibility.html), but makes a graph more interactive.

Examples:
https://codepen.io/jhawes/full/gbPrbZ
https://codepen.io/ksykes/full/mwbZeL

**Comment by jennydove** [comment]
Oh nice - I didn't realize that you have to go to the media library to get to the description. I was trying to find that field yesterday and having no luck. Definitely a good place to start - I can put the full text of some of these into the description too.

**Comment by thetwopct** [comment]
Unfortunately the Gallery Block in the new WordPress editor isn't very intuitive yet and doesn't display the meta tags in the sidebar like other image blocks, and once you've added the image you can't click on it to edit the meta info! So definitely doesn't make it easy.

**Comment by cjyabraham** [comment]
This sounds like a good start.  I'll close this for now but @jennydove let us know if it's worth pursuing some of those other options down the line.
