### ISSUE TITLE
Hover state of buttons in safari looks as if the buttons have been pushed

### ISSUE THREAD

**Issue by cjyabraham** [lfph/lfph.io#54]
the text seems to become smaller on hover

**Comment by cjyabraham** [comment]
weird... now I can't reproduce...

**Comment by thetwopct** [comment]
Yah, I have been seeing the same bug on CNCF last few weeks. Not sure of the cause yet.

On hover, the font state changes - seems to either be the font itself or the sizing. The default Gutenberg CSS is very opinionated, but we really need to keep it for general/ongoing compatibility. Might just need an !important somewhere in the button styling to fix it. Will keep experimenting, but a fix may not come today.

**Comment by thetwopct** [comment]
I've not see this issue happening for a long time, so I am going to close for now.
