### ISSUE TITLE
Make the homepage less stripey

### ISSUE THREAD

**Issue by cjyabraham** [lfph/lfph.io#56]
Consider ways to avoid all the grey stripes on the homepage

**Comment by thetwopct** [comment]
Thoughts: 

Too many CTA sections, and not varied enough. 

The CTA sections are all very similar to each other and with the stripe effect, they **lose** their impact which is I am sure counterintuitive to the intention. 

Some ideas to get around this:

- merge sections together for a more cohesive design
- implement background images / icons to the right of the section to help distinguish them
- switch alignment left and right down the page
- combination of all

We also have a hero section without CTA which looks weird, suggest to add a link to Projects page?

![20200720103946-Linux Foundation Public Health](https://user-images.githubusercontent.com/10615884/87923411-5ab4bc80-ca75-11ea-9c8e-7b870a29be1b.jpg)

**Comment by cjyabraham** [comment]
removing as it has been too long and we haven't heard about this from anyone else
