### ISSUE TITLE
LinkedIn does not show the LFPH card correctly

### ISSUE THREAD

**Issue by dahoum** [lfph/lfph.io#60]
When mentioning lfph.io in a LinkedIn post, under the image of the card it says Homepage and there is no additional text.

When examining lfph.io w/ the Twitter cards validator https://cards-dev.twitter.com/validator the card is shown beautifully.

I am attaching both screenshots.

Could be that LinkedIn needs special treatment.
![B672E0EB-BAA8-403D-AA7C-3C99D36AABCE](https://user-images.githubusercontent.com/23339925/87975564-10aaf580-cacc-11ea-87c2-6e9794eeb2a7.jpeg)
![DD07DB86-A6CC-4929-BF22-26C123874522](https://user-images.githubusercontent.com/23339925/87975579-156fa980-cacc-11ea-8870-c4780820adf5.jpeg)

**Comment by thetwopct** [comment]
Thanks, nice catch. I've updated it and the Linkedin debugger displays an updated version now

https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fwww.lfph.io%2F
