### ISSUE TITLE
Omit "News" from RSS feed?

### ISSUE THREAD

**Issue by thetwopct** [lfph/lfph.io#61]
In the News posts could prove confusing/annoying to users who subscribe to the RSS feed.

Two solutions for starters:

1) Promote the blog only feed - http://lfph.io/blog/feed although the automatic default feed would still include the News posts.

2) Filter out "in the news" category with something like:

```
function lf_remove_news_category($query) {
    if ($query->is_feed) {
        $query->set('cat','-5');  // the category to exclude.
    }
return $query;
}
add_filter('pre_get_posts','lf_remove_news_category');
```

**Comment by cjyabraham** [comment]
[done](https://github.com/cncf/wp-mu-plugins/commit/11f9c655611e45e1f72702c331b480054e6084cf)

**Comment by cjyabraham** [comment]
Deployed.  And I set the RSS icon link in the footer to just /feed instead of /blog/feed.
