### ISSUE TITLE
Stop external link is wrapping on to next line

### ISSUE THREAD

**Issue by thetwopct** [lfph/lfph.io#67]
Thought this had been fixed but looks like its back again, and spacing after the sentence seems to be too much
![20200721224119-Linux Foundation Public Health - Collaborating to battle COVID-19](https://user-images.githubusercontent.com/10615884/88109994-5b4b7100-cba3-11ea-9ffc-04ca5af8e221.jpg)

**Comment by cjyabraham** [comment]
merged, deployed, thumbnails regenerated, image compression in progress...
