### ISSUE TITLE
iFrame Resizer issues

### ISSUE THREAD

**Issue by thetwopct** [lfph/lfph.io#71]
A few issues I noticed popping up on any page embedding the Landscape block. The block is pulling iframeResizer.js from landscape.lfph.io.

`iframeResizer.js:8 [iFrameSizer][Host page: landscape] Deprecated: 'messageCallback' has been renamed 'onMessage'. The old method will be removed in the next major version.`

`DevTools failed to load SourceMap: Could not parse content for https://landscape.lfph.io/iframeResizer.map: Unexpected token < in JSON at position 0`

The script also dumps quite a lot of console messages to the browser, so perhaps `{ log: false }` could be set

![20200724100113-Web Inspector — www lfph io — members](https://user-images.githubusercontent.com/10615884/88376094-abd5f080-cd94-11ea-9c88-5cff8b8cea36.jpg)

**Comment by dankohn** [comment]
Submitted upstream. We'll resolve soon.

**Comment by thetwopct** [comment]
Fixed in https://github.com/cncf/landscapeapp/issues/661
