### ISSUE TITLE
FAQ highlight goes below the fold on small browser heights

### ISSUE THREAD

**Issue by cjyabraham** [lfph/lfph.io#77]
If the browser height is set small, say 511px, then as you scroll down [the FAQ](https://www.lfph.io/join/faq) the highlighted item goes below the fold and you only see it when you get to the bottom of the page:
<img width="1324" alt="Screen Shot 2020-08-04 at 10 52 08 AM" src="https://user-images.githubusercontent.com/463160/89247730-8f617000-d640-11ea-91a4-d15ad6c4a60f.png">

**Comment by thetwopct** [comment]
OK. This is related to the sticky/static nav, and our workaround for that on smaller screen sizes. I should have remembered this would be affected. I've adapted the tab container to stop adding a top value as the user scrolls down, thus keeping it inline with the top of the screen.
