### ISSUE TITLE
Spacing too larger after indented bullets

### ISSUE THREAD

**Issue by cjyabraham** [lfph/lfph.io#8]
When bullets outdent, they leave a large space.  Can it be reduced or eliminated?  See [this page](https://pr-5-lfph.pantheonsite.io/join/projects/):
<img width="639" alt="Screen Shot 2020-06-14 at 2 00 58 PM" src="https://user-images.githubusercontent.com/463160/84585960-8bd31900-ae47-11ea-88a6-408702598499.png">

**Comment by thetwopct** [comment]
Should be consistent now.
