### ISSUE TITLE
Keep the "Register" link on one line instead of wrapping pre-maturely

### ISSUE THREAD

**Issue by cjyabraham** [lfph/lfph.io#86]
See [webinar page](https://www.lfph.io/webinars/introduction-to-lfph/):

<img width="622" alt="Screen Shot 2020-08-11 at 2 23 42 PM" src="https://user-images.githubusercontent.com/463160/89864349-5f851000-dbde-11ea-9cc2-311de1c5274d.png">

**Comment by thetwopct** [comment]
Fixed. My earlier external link wrapping fix caused the issue. The code I added was so the external link icon wouldn't wrap on its own line (using negative margin) but its not working consistently (sometimes the icon is very close to text, sometimes far away). Will look in to it and see if I can work it out.
