### ISSUE TITLE
Fix default thumbnails

### ISSUE THREAD

**Issue by cjyabraham** [lfph/lfph.io#89]
After [this commit](https://github.com/lfph/lfph.io/pull/87/commits/8502243206d73aaa30f5dc3497a87eff17f23b32), the default thumbnail is now too small for [blog posts on the home page](https://dev-lfph.pantheonsite.io/) and [in blog listing](https://dev-lfph.pantheonsite.io/blog/).  Can we restore it to its normal size while not diverging the code from what we have on cncfci?  Perhaps we just need to edit the SVG whitespace of the default thumbnail?
<img width="369" alt="Screen Shot 2020-08-22 at 10 48 51 AM" src="https://user-images.githubusercontent.com/463160/90949125-43079400-e478-11ea-9120-0c63e5609948.png">

**Comment by thetwopct** [comment]
I'd messed up coping across the code between CNCF and LFPH, they are synced now, and the image should be displaying properly on both.

**Comment by cjyabraham** [comment]
The archive pages look good now but the [homepage Announcements block](https://dev-lfph.pantheonsite.io/) still shows rather small logos:
<img width="1082" alt="Screen Shot 2020-08-24 at 10 55 43 AM" src="https://user-images.githubusercontent.com/463160/90999136-5fcad580-e5f8-11ea-9cc9-cf763b5f7788.png">
