### ISSUE TITLE
Show "coming soon" message when there are no upcoming webinars

### ISSUE THREAD

**Issue by cjyabraham** [lfph/lfph.io#91]
Currently on the LFPH site there are no upcoming webinars.  

- [ ] For the homepage block, we should say:
“Stay tuned for new webinars in the coming weeks.  [Sign up for our newsletter](https://www.cncf.io/#newsletter) to stay informed.” with a link going to the footer.

- [ ] On the webinar page we should also show the same message when there are none upcoming.

**Comment by thetwopct** [comment]
Both the front page and the webinars page are using the Upcoming Webinars Block. I've updated it to display a message when there are no webinars upcoming, with a link to the newsletter in the footer.

I ended up adding a border to the message as the text on its own looked lost.

![20200914232406-Linux Foundation Public Health - Collaborating to battle COVID-19](https://user-images.githubusercontent.com/10615884/93139631-658c7600-f6e1-11ea-85b7-3fabdb2d2b37.jpg)

This has been deployed to live. 

The border box is an inline style for now, so feel free to edit / remove if you dislike it. 

The text could be perhaps re-written, the use of "stay" at start and end of the sentence doesn't seem correct to me.

**Comment by cjyabraham** [comment]
Thanks.  I feel the border makes it look a bit boxy.  Any reaction to this style:
<img width="1257" alt="Screen Shot 2020-09-15 at 6 25 54 PM" src="https://user-images.githubusercontent.com/463160/93199495-0c741f00-f781-11ea-81b8-db5b45c59550.png">

Instead of "Stay tuned..." how about "New webinars coming soon..."?

**Comment by thetwopct** [comment]
IMO this looks strange as its just some floating text where otherwise webinar boxes would be. Using the box is more inline with what _should_ be there. But you're the PM, so up to you, its not a big deal.

Current text: 
Stay tuned for new webinars in the coming weeks. Sign up for our newsletter to stay informed.
(duplicate _stay_)

Suggested text:
New webinars coming soon. Sign up for our newsletter to stay informed.

**Comment by cjyabraham** [comment]
I see you set the `italic` css class in your last commit but where is that class defined?  It doesn't render in italics for me.
