### ISSUE TITLE
Favicon and header updates

### ISSUE THREAD

**Issue by thetwopct** [lfph/lfph.io#94]
Safari tab preview image is wrong colour:

![lfph io](https://user-images.githubusercontent.com/10615884/94681612-0c992080-0324-11eb-97bc-9a6ba39e7bb1.jpg)

Coming from this line in the header:

`<link rel="mask-icon" href="/wp-content/themes/lf-theme/images/safari-pinned-tab.svg" color="#de176c">`

Suggest we use #0078f7 blue

Also noticed that:

`<link rel="manifest" href="/wp-content/themes/lf-theme/images/site.webmanifest">` has blank info in the file.

`<meta name="msapplication-TileColor" content="#de176c">` should be blue

**Comment by cjyabraham** [comment]
fixed for all cncf, lfevents and lfph
