### ISSUE TITLE
Spacer blocks overlapping with other blocks in the editor

### ISSUE THREAD

**Issue by cjyabraham** [lfph/lfph.io#97]
Spacer blocks seem to have other blocks overlapping with them.  See [this post](https://www.lfph.io/wp/wp-admin/post.php?post=1222&action=edit).  It doesn't stop you from editing but it doesn't look right:
<img width="1002" alt="Screen Shot 2021-01-12 at 8 28 36 AM" src="https://user-images.githubusercontent.com/463160/104253780-4d224180-54b0-11eb-856d-3d65e6db00d0.png">

**Comment by thetwopct** [comment]
We haven’t copied across updated editor styles to LFPH yet. 

But even on CNCF this is an issue where the Style is overriding the height. I.e height set to 100px, Style is 60px responsive. I haven’t found a way to link style selection and altering the height dimension (and not sure it’s possible)
